### ISSUE TITLE
Setting the viewport width/height via link to values smaller than 0 causes an assert in debug 

### ISSUE THREAD

**Issue by AchimStremplat** [GENIVI/ramses-logic#26]
If the viewport width/height is set via link through the new RamsesCameraBinding to 0, a runtime error is generated (which is nice). But if they are set to values < 0, nothing obvious happens in release and an assert (in  Device_GL::validateDeviceStatusHealthy()) occurs in debug.

The reason seems to be that RamsesCameraBindingImpl::update reads from the bindings a signed int and passes it on as an unsigned int to the Camera::setViewport method.

**Comment by violinyanev** [comment]
That's pretty evil. Fix incoming in 0.6.1!

**Comment by violinyanev** [comment]
Fixed in v0.6.1
