### ISSUE TITLE
Errors regarding viewport width/height in the camera binding accumulate with each update

### ISSUE THREAD

**Issue by AchimStremplat** [GENIVI/ramses-logic#27]
If the viewport width in a camera is set via link to 0, every LogicEngine::update will add another error message for the camera in LogicEngine::getErrors as long as the error persists.

To reproduce: in a new scene in RaCo, add a script with an integer property and create a link from that property to PerspectiveCamera.viewportWidth. Then make sure the property is 0. Create a second script and change its properties. With each change of the second scripts properties, a new entry for the invalid viewport width appears in LogicEngine::getErrors.

**Comment by violinyanev** [comment]
Hi @AchimStremplat ! Thanks for the report, the bug is known and fixed, I was hoping it won't surface until the next release. Will do a patchfix 0.6.1 release!

**Comment by violinyanev** [comment]
Fixed in v0.6.1
